### ISSUE TITLE
#define syntax

### ISSUE THREAD

**Issue by latsa** [senior-zero/cuda_jit#1]
This construct gives syntax errors, because GET_FIRST requires two parameters: 
```
#define GET_FIRST(f, s) f
#define APPLY_TO_PAIR(function, pair) function pair
#define GET_FIRST_FROM_PAIR(pair) APPLY_TO_PAIR(GET_FIRST, pair)
```
What was intended here ^^ ?

Also this:
```
#define DEFER_STRINGIFY(args...) STRINGIFY(args)
#define STRINGIFY(args...) #args
```
should rather be:
```
#define DEFER_STRINGIFY(...) STRINGIFY(__VA_ARGS__)
#define STRINGIFY(...) #__VA_ARGS__
```

**Comment by gevtushenko** [comment]
Hello, according to [this discussion](https://stackoverflow.com/questions/58279658/c-variadic-macro-for-pairs) preprocessor treats balanced parenthesis as a single argument despite containing a comma. As stated in the name of the macro it receives pairs in the form `(type, name)`. After substitution in `APPLY_TO_PAIR` it should be in the form `function (type, name)`, so there are two arguments. Somehow it doesn't work in the VS. As well as the (args...) form of writing a variadic macro. It happened to be an extension that VS doesn't support. 

Thank you for this note, I'll support VS later (or much later).

**Comment by latsa** [comment]
Hello, and thanks for the info. I did a workaround for VS by first letting do the preprocessing with `gcc -E` then copying over the expanded function into the VS project. It compiles now.
