### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by dmadisetti** [senior-zero/cuda_jit#2]
Can you add a license? I would love to be able to use this as a starting point for something else, and want to provide appropriate/full credit.

**Comment by dmadisetti** [comment]
For your reference: https://github.com/senior-zero/cuda_jit/community/license/new?branch=master

**Comment by gevtushenko** [comment]
> For your reference: https://github.com/senior-zero/cuda_jit/community/license/new?branch=master

Hello, @dmadisetti! Thank you for this note. I've set the MIT licence. I hope you find it suitable.

**Comment by dmadisetti** [comment]
Perfect! Thank you
